name       : pyorbit
version    : 2.24.0
release    : 2
source     :
    - http://ftp.acc.umu.se/pub/GNOME/sources/pyorbit/2.24/pyorbit-2.24.0.tar.bz2 : 8754669b8220aa1f151b920360029d5ea28c42bec55769059676725fe28397b8
license    : LGPL-2.1
summary    : Python Orbit2 binding.
component  : programming.python
description: |
    This is a Python language binding for the ORBit2 CORBA implementation.
builddeps  :
    - pkgconfig(ORBit-2.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
